Item.create(name: "Prislusenstvo")
Item.create(name: "Pokrývky hlavy")
Item.create(name: "Rukavice")
Item.create(name: "Oblecenie")
Item.create(name: "Nohavice", parent: Item.find_by_name("Oblecenie"))
Item.create(name: "Tricko", parent: Item.find_by_name("Oblecenie"))
Item.create(name: "Topanky")
Item.create(name: "Tenisky", parent: Item.find_by_name("Topanky"))
Item.create(name: "Papuce", parent: Item.find_by_name("Topanky"))
Item.create(name: "Papucky", parent: Item.find_by_name("Papuce"))
Item.create(name: "Noznice")
Item.create(name: "Bojove", parent: Item.find_by_name("Pokrývky hlavy"))
Item.create(name: "Helma", parent: Item.find_by_name("Bojove"))
Item.create(name: "Rekreacne", parent: Item.find_by_name("Pokrývky hlavy"))
Item.create(name: "Na vonok", parent: Item.find_by_name("Rekreacne"))
Item.create(name: "Farebne", parent: Item.find_by_name("Na vonok"))
Item.create(name: "Modra", parent: Item.find_by_name("Farebne"))
Item.create(name: "Zelena", parent: Item.find_by_name("Farebne"))
Item.create(name: "Cierna", parent: Item.find_by_name("Farebne"))
Item.create(name: "Cervena", parent: Item.find_by_name("Farebne"))